/*
 * generated by Xtext 2.34.0
 */
package ics.helper.parser.antlr;

import com.google.inject.Inject;
import ics.helper.parser.antlr.internal.InternalHelperDSLParser;
import ics.helper.services.HelperDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class HelperDSLParser extends AbstractAntlrParser {

	@Inject
	private HelperDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHelperDSLParser createParser(XtextTokenStream stream) {
		return new InternalHelperDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public HelperDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HelperDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
