/*
 * generated by Xtext 2.34.0
 */
package ics.helper.ui;

import com.google.inject.Injector;
import ics.helper.ui.internal.HelperActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HelperDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(HelperActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		HelperActivator activator = HelperActivator.getInstance();
		return activator != null ? activator.getInjector(HelperActivator.ICS_HELPER_HELPERDSL) : null;
	}

}
