/*
 * generated by Xtext 2.34.0
 */
package ics.helper.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHelperDSLScopeProvider extends DelegatingScopeProvider {
}
