/*
 * generated by Xtext 2.34.0
 */
package ics.helper.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class HelperDSLProposalProvider extends AbstractHelperDSLProposalProvider {
}
