/**
 * generated by Xtext 2.34.0
 */
package ics.helper.helperDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ics.helper.helperDSL.HelperDSLPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
} // Command
