/**
 * generated by Xtext 2.34.0
 */
package ics.helper.helperDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Days Of Week</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ics.helper.helperDSL.DaysOfWeek#getDays <em>Days</em>}</li>
 * </ul>
 *
 * @see ics.helper.helperDSL.HelperDSLPackage#getDaysOfWeek()
 * @model
 * @generated
 */
public interface DaysOfWeek extends EObject
{
  /**
   * Returns the value of the '<em><b>Days</b></em>' attribute list.
   * The list contents are of type {@link ics.helper.helperDSL.WEEKDAY}.
   * The literals are from the enumeration {@link ics.helper.helperDSL.WEEKDAY}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Days</em>' attribute list.
   * @see ics.helper.helperDSL.WEEKDAY
   * @see ics.helper.helperDSL.HelperDSLPackage#getDaysOfWeek_Days()
   * @model unique="false"
   * @generated
   */
  EList<WEEKDAY> getDays();

} // DaysOfWeek
