/**
 * generated by Xtext 2.34.0
 */
package ics.helper.helperDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ics.helper.helperDSL.Event#getName <em>Name</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getStartTime <em>Start Time</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getEndTime <em>End Time</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getLocation <em>Location</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getDescription <em>Description</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getRecur <em>Recur</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getDaysOfWeek <em>Days Of Week</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getLink <em>Link</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getOrganizer <em>Organizer</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getInvitees <em>Invitees</em>}</li>
 *   <li>{@link ics.helper.helperDSL.Event#getReminder <em>Reminder</em>}</li>
 * </ul>
 *
 * @see ics.helper.helperDSL.HelperDSLPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Time</em>' attribute.
   * @see #setStartTime(String)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_StartTime()
   * @model
   * @generated
   */
  String getStartTime();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getStartTime <em>Start Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Time</em>' attribute.
   * @see #getStartTime()
   * @generated
   */
  void setStartTime(String value);

  /**
   * Returns the value of the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Time</em>' attribute.
   * @see #setEndTime(String)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_EndTime()
   * @model
   * @generated
   */
  String getEndTime();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getEndTime <em>End Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Time</em>' attribute.
   * @see #getEndTime()
   * @generated
   */
  void setEndTime(String value);

  /**
   * Returns the value of the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' attribute.
   * @see #setLocation(String)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_Location()
   * @model
   * @generated
   */
  String getLocation();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getLocation <em>Location</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location</em>' attribute.
   * @see #getLocation()
   * @generated
   */
  void setLocation(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Recur</b></em>' attribute.
   * The literals are from the enumeration {@link ics.helper.helperDSL.RecurRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recur</em>' attribute.
   * @see ics.helper.helperDSL.RecurRule
   * @see #setRecur(RecurRule)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_Recur()
   * @model
   * @generated
   */
  RecurRule getRecur();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getRecur <em>Recur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Recur</em>' attribute.
   * @see ics.helper.helperDSL.RecurRule
   * @see #getRecur()
   * @generated
   */
  void setRecur(RecurRule value);

  /**
   * Returns the value of the '<em><b>Days Of Week</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Days Of Week</em>' containment reference.
   * @see #setDaysOfWeek(DaysOfWeek)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_DaysOfWeek()
   * @model containment="true"
   * @generated
   */
  DaysOfWeek getDaysOfWeek();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getDaysOfWeek <em>Days Of Week</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Days Of Week</em>' containment reference.
   * @see #getDaysOfWeek()
   * @generated
   */
  void setDaysOfWeek(DaysOfWeek value);

  /**
   * Returns the value of the '<em><b>Link</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link</em>' attribute.
   * @see #setLink(String)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_Link()
   * @model
   * @generated
   */
  String getLink();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getLink <em>Link</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link</em>' attribute.
   * @see #getLink()
   * @generated
   */
  void setLink(String value);

  /**
   * Returns the value of the '<em><b>Organizer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Organizer</em>' containment reference.
   * @see #setOrganizer(Person)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_Organizer()
   * @model containment="true"
   * @generated
   */
  Person getOrganizer();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getOrganizer <em>Organizer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Organizer</em>' containment reference.
   * @see #getOrganizer()
   * @generated
   */
  void setOrganizer(Person value);

  /**
   * Returns the value of the '<em><b>Invitees</b></em>' containment reference list.
   * The list contents are of type {@link ics.helper.helperDSL.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invitees</em>' containment reference list.
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_Invitees()
   * @model containment="true"
   * @generated
   */
  EList<Person> getInvitees();

  /**
   * Returns the value of the '<em><b>Reminder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reminder</em>' containment reference.
   * @see #setReminder(Reminder)
   * @see ics.helper.helperDSL.HelperDSLPackage#getEvent_Reminder()
   * @model containment="true"
   * @generated
   */
  Reminder getReminder();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.Event#getReminder <em>Reminder</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reminder</em>' containment reference.
   * @see #getReminder()
   * @generated
   */
  void setReminder(Reminder value);

} // Event
