/**
 * generated by Xtext 2.34.0
 */
package ics.helper.helperDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ics.helper.helperDSL.HelperDSLFactory
 * @model kind="package"
 * @generated
 */
public interface HelperDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "helperDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.helper.ics/HelperDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "helperDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HelperDSLPackage eINSTANCE = ics.helper.helperDSL.impl.HelperDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.ModelImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.CommandImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.CreateCommandImpl <em>Create Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.CreateCommandImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getCreateCommand()
   * @generated
   */
  int CREATE_COMMAND = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_COMMAND__NAME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_COMMAND__EVENTS = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Create Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.EventImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__START_TIME = 1;

  /**
   * The feature id for the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__END_TIME = 2;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__LOCATION = 3;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__DESCRIPTION = 4;

  /**
   * The feature id for the '<em><b>Recur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__RECUR = 5;

  /**
   * The feature id for the '<em><b>Days Of Week</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__DAYS_OF_WEEK = 6;

  /**
   * The feature id for the '<em><b>Link</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__LINK = 7;

  /**
   * The feature id for the '<em><b>Organizer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__ORGANIZER = 8;

  /**
   * The feature id for the '<em><b>Invitees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__INVITEES = 9;

  /**
   * The feature id for the '<em><b>Reminder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__REMINDER = 10;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.ReminderImpl <em>Reminder</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.ReminderImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getReminder()
   * @generated
   */
  int REMINDER = 4;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMINDER__TIME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMINDER__TITLE = 1;

  /**
   * The number of structural features of the '<em>Reminder</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMINDER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.PersonImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__EMAIL = 1;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.DaysOfWeekImpl <em>Days Of Week</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.DaysOfWeekImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getDaysOfWeek()
   * @generated
   */
  int DAYS_OF_WEEK = 6;

  /**
   * The feature id for the '<em><b>Days</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DAYS_OF_WEEK__DAYS = 0;

  /**
   * The number of structural features of the '<em>Days Of Week</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DAYS_OF_WEEK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.ScheduleImpl <em>Schedule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.ScheduleImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getSchedule()
   * @generated
   */
  int SCHEDULE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE__NAME = 0;

  /**
   * The number of structural features of the '<em>Schedule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.SplitCommandImpl <em>Split Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.SplitCommandImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getSplitCommand()
   * @generated
   */
  int SPLIT_COMMAND = 8;

  /**
   * The feature id for the '<em><b>Schedule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_COMMAND__SCHEDULE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Criteria</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_COMMAND__CRITERIA = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Split Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.MergeCommandImpl <em>Merge Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.MergeCommandImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getMergeCommand()
   * @generated
   */
  int MERGE_COMMAND = 9;

  /**
   * The feature id for the '<em><b>Schedules</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MERGE_COMMAND__SCHEDULES = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MERGE_COMMAND__TARGET = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Merge Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MERGE_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.impl.ModifyCommandImpl <em>Modify Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.impl.ModifyCommandImpl
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getModifyCommand()
   * @generated
   */
  int MODIFY_COMMAND = 10;

  /**
   * The feature id for the '<em><b>Schedule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND__SCHEDULE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND__EVENT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND__TIME = COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND__VALUE = COMMAND_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Modify Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.RecurRule <em>Recur Rule</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.RecurRule
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getRecurRule()
   * @generated
   */
  int RECUR_RULE = 11;

  /**
   * The meta object id for the '{@link ics.helper.helperDSL.WEEKDAY <em>WEEKDAY</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ics.helper.helperDSL.WEEKDAY
   * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getWEEKDAY()
   * @generated
   */
  int WEEKDAY = 12;


  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see ics.helper.helperDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link ics.helper.helperDSL.Model#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see ics.helper.helperDSL.Model#getCommands()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Commands();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see ics.helper.helperDSL.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.CreateCommand <em>Create Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Command</em>'.
   * @see ics.helper.helperDSL.CreateCommand
   * @generated
   */
  EClass getCreateCommand();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.CreateCommand#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ics.helper.helperDSL.CreateCommand#getName()
   * @see #getCreateCommand()
   * @generated
   */
  EAttribute getCreateCommand_Name();

  /**
   * Returns the meta object for the containment reference list '{@link ics.helper.helperDSL.CreateCommand#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see ics.helper.helperDSL.CreateCommand#getEvents()
   * @see #getCreateCommand()
   * @generated
   */
  EReference getCreateCommand_Events();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see ics.helper.helperDSL.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ics.helper.helperDSL.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Event#getStartTime <em>Start Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Time</em>'.
   * @see ics.helper.helperDSL.Event#getStartTime()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_StartTime();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Event#getEndTime <em>End Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Time</em>'.
   * @see ics.helper.helperDSL.Event#getEndTime()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_EndTime();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Event#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see ics.helper.helperDSL.Event#getLocation()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Location();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Event#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see ics.helper.helperDSL.Event#getDescription()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Description();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Event#getRecur <em>Recur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Recur</em>'.
   * @see ics.helper.helperDSL.Event#getRecur()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Recur();

  /**
   * Returns the meta object for the containment reference '{@link ics.helper.helperDSL.Event#getDaysOfWeek <em>Days Of Week</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Days Of Week</em>'.
   * @see ics.helper.helperDSL.Event#getDaysOfWeek()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_DaysOfWeek();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Event#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link</em>'.
   * @see ics.helper.helperDSL.Event#getLink()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Link();

  /**
   * Returns the meta object for the containment reference '{@link ics.helper.helperDSL.Event#getOrganizer <em>Organizer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Organizer</em>'.
   * @see ics.helper.helperDSL.Event#getOrganizer()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Organizer();

  /**
   * Returns the meta object for the containment reference list '{@link ics.helper.helperDSL.Event#getInvitees <em>Invitees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Invitees</em>'.
   * @see ics.helper.helperDSL.Event#getInvitees()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Invitees();

  /**
   * Returns the meta object for the containment reference '{@link ics.helper.helperDSL.Event#getReminder <em>Reminder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reminder</em>'.
   * @see ics.helper.helperDSL.Event#getReminder()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Reminder();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.Reminder <em>Reminder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reminder</em>'.
   * @see ics.helper.helperDSL.Reminder
   * @generated
   */
  EClass getReminder();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Reminder#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see ics.helper.helperDSL.Reminder#getTime()
   * @see #getReminder()
   * @generated
   */
  EAttribute getReminder_Time();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Reminder#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see ics.helper.helperDSL.Reminder#getTitle()
   * @see #getReminder()
   * @generated
   */
  EAttribute getReminder_Title();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see ics.helper.helperDSL.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ics.helper.helperDSL.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Person#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see ics.helper.helperDSL.Person#getEmail()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Email();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.DaysOfWeek <em>Days Of Week</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Days Of Week</em>'.
   * @see ics.helper.helperDSL.DaysOfWeek
   * @generated
   */
  EClass getDaysOfWeek();

  /**
   * Returns the meta object for the attribute list '{@link ics.helper.helperDSL.DaysOfWeek#getDays <em>Days</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Days</em>'.
   * @see ics.helper.helperDSL.DaysOfWeek#getDays()
   * @see #getDaysOfWeek()
   * @generated
   */
  EAttribute getDaysOfWeek_Days();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.Schedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schedule</em>'.
   * @see ics.helper.helperDSL.Schedule
   * @generated
   */
  EClass getSchedule();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.Schedule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ics.helper.helperDSL.Schedule#getName()
   * @see #getSchedule()
   * @generated
   */
  EAttribute getSchedule_Name();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.SplitCommand <em>Split Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Split Command</em>'.
   * @see ics.helper.helperDSL.SplitCommand
   * @generated
   */
  EClass getSplitCommand();

  /**
   * Returns the meta object for the reference '{@link ics.helper.helperDSL.SplitCommand#getSchedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Schedule</em>'.
   * @see ics.helper.helperDSL.SplitCommand#getSchedule()
   * @see #getSplitCommand()
   * @generated
   */
  EReference getSplitCommand_Schedule();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.SplitCommand#getCriteria <em>Criteria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Criteria</em>'.
   * @see ics.helper.helperDSL.SplitCommand#getCriteria()
   * @see #getSplitCommand()
   * @generated
   */
  EAttribute getSplitCommand_Criteria();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.MergeCommand <em>Merge Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Merge Command</em>'.
   * @see ics.helper.helperDSL.MergeCommand
   * @generated
   */
  EClass getMergeCommand();

  /**
   * Returns the meta object for the reference list '{@link ics.helper.helperDSL.MergeCommand#getSchedules <em>Schedules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Schedules</em>'.
   * @see ics.helper.helperDSL.MergeCommand#getSchedules()
   * @see #getMergeCommand()
   * @generated
   */
  EReference getMergeCommand_Schedules();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.MergeCommand#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see ics.helper.helperDSL.MergeCommand#getTarget()
   * @see #getMergeCommand()
   * @generated
   */
  EAttribute getMergeCommand_Target();

  /**
   * Returns the meta object for class '{@link ics.helper.helperDSL.ModifyCommand <em>Modify Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modify Command</em>'.
   * @see ics.helper.helperDSL.ModifyCommand
   * @generated
   */
  EClass getModifyCommand();

  /**
   * Returns the meta object for the reference '{@link ics.helper.helperDSL.ModifyCommand#getSchedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Schedule</em>'.
   * @see ics.helper.helperDSL.ModifyCommand#getSchedule()
   * @see #getModifyCommand()
   * @generated
   */
  EReference getModifyCommand_Schedule();

  /**
   * Returns the meta object for the reference '{@link ics.helper.helperDSL.ModifyCommand#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see ics.helper.helperDSL.ModifyCommand#getEvent()
   * @see #getModifyCommand()
   * @generated
   */
  EReference getModifyCommand_Event();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.ModifyCommand#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see ics.helper.helperDSL.ModifyCommand#getTime()
   * @see #getModifyCommand()
   * @generated
   */
  EAttribute getModifyCommand_Time();

  /**
   * Returns the meta object for the attribute '{@link ics.helper.helperDSL.ModifyCommand#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ics.helper.helperDSL.ModifyCommand#getValue()
   * @see #getModifyCommand()
   * @generated
   */
  EAttribute getModifyCommand_Value();

  /**
   * Returns the meta object for enum '{@link ics.helper.helperDSL.RecurRule <em>Recur Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Recur Rule</em>'.
   * @see ics.helper.helperDSL.RecurRule
   * @generated
   */
  EEnum getRecurRule();

  /**
   * Returns the meta object for enum '{@link ics.helper.helperDSL.WEEKDAY <em>WEEKDAY</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>WEEKDAY</em>'.
   * @see ics.helper.helperDSL.WEEKDAY
   * @generated
   */
  EEnum getWEEKDAY();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HelperDSLFactory getHelperDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.ModelImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMMANDS = eINSTANCE.getModel_Commands();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.CommandImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.CreateCommandImpl <em>Create Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.CreateCommandImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getCreateCommand()
     * @generated
     */
    EClass CREATE_COMMAND = eINSTANCE.getCreateCommand();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE_COMMAND__NAME = eINSTANCE.getCreateCommand_Name();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_COMMAND__EVENTS = eINSTANCE.getCreateCommand_Events();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.EventImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Start Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__START_TIME = eINSTANCE.getEvent_StartTime();

    /**
     * The meta object literal for the '<em><b>End Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__END_TIME = eINSTANCE.getEvent_EndTime();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__LOCATION = eINSTANCE.getEvent_Location();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__DESCRIPTION = eINSTANCE.getEvent_Description();

    /**
     * The meta object literal for the '<em><b>Recur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__RECUR = eINSTANCE.getEvent_Recur();

    /**
     * The meta object literal for the '<em><b>Days Of Week</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__DAYS_OF_WEEK = eINSTANCE.getEvent_DaysOfWeek();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__LINK = eINSTANCE.getEvent_Link();

    /**
     * The meta object literal for the '<em><b>Organizer</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__ORGANIZER = eINSTANCE.getEvent_Organizer();

    /**
     * The meta object literal for the '<em><b>Invitees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__INVITEES = eINSTANCE.getEvent_Invitees();

    /**
     * The meta object literal for the '<em><b>Reminder</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__REMINDER = eINSTANCE.getEvent_Reminder();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.ReminderImpl <em>Reminder</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.ReminderImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getReminder()
     * @generated
     */
    EClass REMINDER = eINSTANCE.getReminder();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMINDER__TIME = eINSTANCE.getReminder_Time();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMINDER__TITLE = eINSTANCE.getReminder_Title();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.PersonImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__EMAIL = eINSTANCE.getPerson_Email();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.DaysOfWeekImpl <em>Days Of Week</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.DaysOfWeekImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getDaysOfWeek()
     * @generated
     */
    EClass DAYS_OF_WEEK = eINSTANCE.getDaysOfWeek();

    /**
     * The meta object literal for the '<em><b>Days</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DAYS_OF_WEEK__DAYS = eINSTANCE.getDaysOfWeek_Days();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.ScheduleImpl <em>Schedule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.ScheduleImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getSchedule()
     * @generated
     */
    EClass SCHEDULE = eINSTANCE.getSchedule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEDULE__NAME = eINSTANCE.getSchedule_Name();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.SplitCommandImpl <em>Split Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.SplitCommandImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getSplitCommand()
     * @generated
     */
    EClass SPLIT_COMMAND = eINSTANCE.getSplitCommand();

    /**
     * The meta object literal for the '<em><b>Schedule</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPLIT_COMMAND__SCHEDULE = eINSTANCE.getSplitCommand_Schedule();

    /**
     * The meta object literal for the '<em><b>Criteria</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPLIT_COMMAND__CRITERIA = eINSTANCE.getSplitCommand_Criteria();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.MergeCommandImpl <em>Merge Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.MergeCommandImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getMergeCommand()
     * @generated
     */
    EClass MERGE_COMMAND = eINSTANCE.getMergeCommand();

    /**
     * The meta object literal for the '<em><b>Schedules</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MERGE_COMMAND__SCHEDULES = eINSTANCE.getMergeCommand_Schedules();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MERGE_COMMAND__TARGET = eINSTANCE.getMergeCommand_Target();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.impl.ModifyCommandImpl <em>Modify Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.impl.ModifyCommandImpl
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getModifyCommand()
     * @generated
     */
    EClass MODIFY_COMMAND = eINSTANCE.getModifyCommand();

    /**
     * The meta object literal for the '<em><b>Schedule</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODIFY_COMMAND__SCHEDULE = eINSTANCE.getModifyCommand_Schedule();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODIFY_COMMAND__EVENT = eINSTANCE.getModifyCommand_Event();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODIFY_COMMAND__TIME = eINSTANCE.getModifyCommand_Time();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODIFY_COMMAND__VALUE = eINSTANCE.getModifyCommand_Value();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.RecurRule <em>Recur Rule</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.RecurRule
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getRecurRule()
     * @generated
     */
    EEnum RECUR_RULE = eINSTANCE.getRecurRule();

    /**
     * The meta object literal for the '{@link ics.helper.helperDSL.WEEKDAY <em>WEEKDAY</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ics.helper.helperDSL.WEEKDAY
     * @see ics.helper.helperDSL.impl.HelperDSLPackageImpl#getWEEKDAY()
     * @generated
     */
    EEnum WEEKDAY = eINSTANCE.getWEEKDAY();

  }

} //HelperDSLPackage
