/**
 * generated by Xtext 2.34.0
 */
package ics.helper.helperDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Merge Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ics.helper.helperDSL.MergeCommand#getSchedules <em>Schedules</em>}</li>
 *   <li>{@link ics.helper.helperDSL.MergeCommand#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see ics.helper.helperDSL.HelperDSLPackage#getMergeCommand()
 * @model
 * @generated
 */
public interface MergeCommand extends Command
{
  /**
   * Returns the value of the '<em><b>Schedules</b></em>' reference list.
   * The list contents are of type {@link ics.helper.helperDSL.Schedule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schedules</em>' reference list.
   * @see ics.helper.helperDSL.HelperDSLPackage#getMergeCommand_Schedules()
   * @model
   * @generated
   */
  EList<Schedule> getSchedules();

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see ics.helper.helperDSL.HelperDSLPackage#getMergeCommand_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.MergeCommand#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

} // MergeCommand
