/**
 * generated by Xtext 2.34.0
 */
package ics.helper.helperDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Split Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ics.helper.helperDSL.SplitCommand#getSchedule <em>Schedule</em>}</li>
 *   <li>{@link ics.helper.helperDSL.SplitCommand#getCriteria <em>Criteria</em>}</li>
 * </ul>
 *
 * @see ics.helper.helperDSL.HelperDSLPackage#getSplitCommand()
 * @model
 * @generated
 */
public interface SplitCommand extends Command
{
  /**
   * Returns the value of the '<em><b>Schedule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schedule</em>' reference.
   * @see #setSchedule(Schedule)
   * @see ics.helper.helperDSL.HelperDSLPackage#getSplitCommand_Schedule()
   * @model
   * @generated
   */
  Schedule getSchedule();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.SplitCommand#getSchedule <em>Schedule</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schedule</em>' reference.
   * @see #getSchedule()
   * @generated
   */
  void setSchedule(Schedule value);

  /**
   * Returns the value of the '<em><b>Criteria</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Criteria</em>' attribute.
   * @see #setCriteria(String)
   * @see ics.helper.helperDSL.HelperDSLPackage#getSplitCommand_Criteria()
   * @model
   * @generated
   */
  String getCriteria();

  /**
   * Sets the value of the '{@link ics.helper.helperDSL.SplitCommand#getCriteria <em>Criteria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Criteria</em>' attribute.
   * @see #getCriteria()
   * @generated
   */
  void setCriteria(String value);

} // SplitCommand
