/*
 * generated by Xtext 2.34.0
 */
package ics.helper.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HelperDSLUiModule extends AbstractHelperDSLUiModule {

	public HelperDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
